DOMAIN = "helman"
NAME = "Helman Energy"
CUSTOM_COMPONENTS = "custom_components"
STORAGE_VERSION = 1
STORAGE_KEY = f"{DOMAIN}.config"
FORECAST_SNAPSHOT_STORAGE_KEY = f"{DOMAIN}.forecast_snapshot"
FORECAST_SNAPSHOT_STORAGE_VERSION = 1
SCHEDULE_STORAGE_KEY = f"{DOMAIN}.schedule"
SCHEDULE_STORAGE_VERSION = 1
BATTERY_FORECAST_HISTORY_STORAGE_KEY = f"{DOMAIN}.battery_forecast_history"
BATTERY_FORECAST_HISTORY_STORAGE_VERSION = 1
BATTERY_FORECAST_HISTORY_RETENTION_DAYS = 90
DAY_CONTEXT_STORAGE_KEY = f"{DOMAIN}.day_context"
DAY_CONTEXT_STORAGE_VERSION = 1
DAY_CLASSIFICATION_SURPLUS = "surplus"
DAY_CLASSIFICATION_TIGHT = "tight"
DAY_CLASSIFICATION_DEFICIT = "deficit"
# Version of the stored config document. Bumped when a stored shape changes in
# a way that needs migrating on load; absent means version 1 (pre-unification).
CONFIG_DOCUMENT_VERSION = 3

DAY_CLASSIFICATIONS = (
    DAY_CLASSIFICATION_SURPLUS,
    DAY_CLASSIFICATION_TIGHT,
    DAY_CLASSIFICATION_DEFICIT,
)
DAY_CONTEXT_DEFAULT_DEFICIT_BELOW_RATIO = 0.7
DAY_CONTEXT_DEFAULT_SURPLUS_ABOVE_RATIO = 1.3
IMPORT_BAND_LEVEL_CHEAP = "cheap"
IMPORT_BAND_LEVEL_EXPENSIVE = "expensive"
SCHEDULE_SLOT_MINUTES = 30
SCHEDULE_HORIZON_HOURS = 48
SCHEDULE_ACTION_EMPTY = "empty"
SCHEDULE_ACTION_NORMAL = "normal"
SCHEDULE_ACTION_CHARGE_TO_TARGET_SOC = "charge_to_target_soc"
SCHEDULE_ACTION_DISCHARGE_TO_TARGET_SOC = "discharge_to_target_soc"
SCHEDULE_ACTION_STOP_CHARGING = "stop_charging"
SCHEDULE_ACTION_STOP_DISCHARGING = "stop_discharging"
SCHEDULE_ACTION_STOP_EXPORT = "stop_export"
SCHEDULE_ACTION_KINDS = {
    SCHEDULE_ACTION_EMPTY,
    SCHEDULE_ACTION_NORMAL,
    SCHEDULE_ACTION_CHARGE_TO_TARGET_SOC,
    SCHEDULE_ACTION_DISCHARGE_TO_TARGET_SOC,
    SCHEDULE_ACTION_STOP_CHARGING,
    SCHEDULE_ACTION_STOP_DISCHARGING,
    SCHEDULE_ACTION_STOP_EXPORT,
}
SCHEDULE_EXECUTOR_INTERVAL_SECONDS = 30
# Freshness window for the pre-execution reality check: when the current plan is
# younger than this, the executor trusts its condition_met stamps as-is. Only
# when the plan is older does the executor re-evaluate conditions and, if any
# result differs from the plan, defer execution and re-plan first. Must comfort-
# ably exceed a re-plan's duration so the re-plan -> execute hop settles inside
# the window and does not bounce back and forth.
AUTOMATION_CONDITION_PLAN_FRESHNESS_SECONDS = 30
CONSUMPTION_TOTAL_ENTITY_ID = "sensor.helman_consumption_total"
PRODUCTION_TOTAL_ENTITY_ID = "sensor.helman_production_total"
HOUSE_FORECAST_DEFAULT_MIN_HISTORY_DAYS = 14
HOUSE_FORECAST_DEFAULT_TRAINING_WINDOW_DAYS = 56
HOUSE_FORECAST_DEFAULT_MIN_SLOT_POINTS = 2
HOUSE_FORECAST_LOWER_PERCENTILE = 0.10
HOUSE_FORECAST_UPPER_PERCENTILE = 0.90
HOUSE_FORECAST_MODEL_ID = "hour_of_week_winsorized_mean"
FORECAST_CANONICAL_GRANULARITY_MINUTES = 15
FORECAST_GRANULARITY_OPTIONS = (15, 30, 60)
DEFAULT_FORECAST_GRANULARITY_MINUTES = 60
DEFAULT_FORECAST_DAYS = 7
MAX_FORECAST_DAYS = 14
BATTERY_CAPACITY_FORECAST_CACHE_TTL_SECONDS = 300
BATTERY_CAPACITY_FORECAST_DEFAULT_CHARGE_EFFICIENCY = 0.95
BATTERY_CAPACITY_FORECAST_DEFAULT_DISCHARGE_EFFICIENCY = 0.95
BATTERY_CAPACITY_FORECAST_MODEL_ID = "battery_net_load_fractional_hour_v1"
DEFAULT_APPLIANCE_ICON = "mdi:lightning-bolt"

# Compiled frontend (card + config editor), served as static files
FRONTEND_COMPILED_FOLDER = "frontend_compiled"
FRONTEND_URL_BASE = "/helman_frontend"
CARD_FILENAME = "helman-card.js"
CARD_URL = f"{FRONTEND_URL_BASE}/{CARD_FILENAME}"

PANEL_FILENAME = "helman-config-editor.js"
PANEL_URL = f"/api/panel_custom/{DOMAIN}-config"
PANEL_TITLE = f"{NAME} Config"
PANEL_ICON = "mdi:home-lightning-bolt-outline"
PANEL_NAME = "helman-config-editor-panel"
PANEL_FRONTEND_URL_PATH = f"{DOMAIN}-config"

# Solar bias correction storage defaults and keys
SOLAR_BIAS_STORAGE_KEY = f"{DOMAIN}.solar_bias_correction"
SOLAR_BIAS_STORAGE_VERSION = 2
SOLAR_BIAS_SUPPORTED_STORE_VERSION = 2
SOLAR_BIAS_DEFAULT_ENABLED = True
SOLAR_BIAS_DEFAULT_MIN_HISTORY_DAYS = 10
SOLAR_BIAS_DEFAULT_MAX_TRAINING_WINDOW_DAYS = 90
SOLAR_BIAS_DEFAULT_TRAINING_TIME = "03:00"
SOLAR_BIAS_DEFAULT_CLAMP_MIN = 0.0
SOLAR_BIAS_DEFAULT_CLAMP_MAX = 3.0
SOLAR_BIAS_DEFAULT_MIN_VALID_SLOT_DAYS = 5
SOLAR_BIAS_DEFAULT_AGGREGATION_METHOD = "ratio_of_sums"
SOLAR_BIAS_DEFAULT_MAX_INTERPOLATED_CONSECUTIVE_SLOTS = 2
SOLAR_BIAS_AGGREGATION_METHODS = ("ratio_of_sums", "trimmed_mean")
