DOMAIN = "helman"
NAME = "Helman Energy"
STORAGE_VERSION = 1
STORAGE_KEY = f"{DOMAIN}.config"
FORECAST_SNAPSHOT_STORAGE_KEY = f"{DOMAIN}.forecast_snapshot"
FORECAST_SNAPSHOT_STORAGE_VERSION = 1
SCHEDULE_STORAGE_KEY = f"{DOMAIN}.schedule"
SCHEDULE_STORAGE_VERSION = 1
SCHEDULE_SLOT_MINUTES = 30
SCHEDULE_HORIZON_HOURS = 48
SCHEDULE_ACTION_NORMAL = "normal"
SCHEDULE_ACTION_CHARGE_TO_TARGET_SOC = "charge_to_target_soc"
SCHEDULE_ACTION_DISCHARGE_TO_TARGET_SOC = "discharge_to_target_soc"
SCHEDULE_ACTION_STOP_CHARGING = "stop_charging"
SCHEDULE_ACTION_STOP_DISCHARGING = "stop_discharging"
SCHEDULE_ACTION_KINDS = {
    SCHEDULE_ACTION_NORMAL,
    SCHEDULE_ACTION_CHARGE_TO_TARGET_SOC,
    SCHEDULE_ACTION_DISCHARGE_TO_TARGET_SOC,
    SCHEDULE_ACTION_STOP_CHARGING,
    SCHEDULE_ACTION_STOP_DISCHARGING,
}
SCHEDULE_EXECUTOR_INTERVAL_SECONDS = 30
CONSUMPTION_TOTAL_ENTITY_ID = "sensor.helman_consumption_total"
PRODUCTION_TOTAL_ENTITY_ID = "sensor.helman_production_total"
HOUSE_FORECAST_DEFAULT_MIN_HISTORY_DAYS = 14
HOUSE_FORECAST_DEFAULT_TRAINING_WINDOW_DAYS = 56
HOUSE_FORECAST_DEFAULT_MIN_SLOT_POINTS = 2
HOUSE_FORECAST_LOWER_PERCENTILE = 0.10
HOUSE_FORECAST_UPPER_PERCENTILE = 0.90
HOUSE_FORECAST_MODEL_ID = "hour_of_week_winsorized_mean"
BATTERY_CAPACITY_FORECAST_HORIZON_HOURS = 168
BATTERY_CAPACITY_FORECAST_CACHE_TTL_SECONDS = 300
BATTERY_CAPACITY_FORECAST_DEFAULT_CHARGE_EFFICIENCY = 0.95
BATTERY_CAPACITY_FORECAST_DEFAULT_DISCHARGE_EFFICIENCY = 0.95
BATTERY_CAPACITY_FORECAST_MODEL_ID = "battery_net_load_fractional_hour_v1"
