DOMAIN = "helman"
NAME = "Helman Energy"
CUSTOM_COMPONENTS = "custom_components"
STORAGE_VERSION = 1
STORAGE_KEY = f"{DOMAIN}.config"
FORECAST_SNAPSHOT_STORAGE_KEY = f"{DOMAIN}.forecast_snapshot"
FORECAST_SNAPSHOT_STORAGE_VERSION = 1
SCHEDULE_STORAGE_KEY = f"{DOMAIN}.schedule"
SCHEDULE_STORAGE_VERSION = 1
SCHEDULE_SLOT_MINUTES = 30
SCHEDULE_HORIZON_HOURS = 48
SCHEDULE_ACTION_EMPTY = "empty"
SCHEDULE_ACTION_NORMAL = "normal"
SCHEDULE_ACTION_CHARGE_TO_TARGET_SOC = "charge_to_target_soc"
SCHEDULE_ACTION_DISCHARGE_TO_TARGET_SOC = "discharge_to_target_soc"
SCHEDULE_ACTION_STOP_CHARGING = "stop_charging"
SCHEDULE_ACTION_STOP_DISCHARGING = "stop_discharging"
SCHEDULE_ACTION_STOP_EXPORT = "stop_export"
SCHEDULE_ACTION_KINDS = {
    SCHEDULE_ACTION_EMPTY,
    SCHEDULE_ACTION_NORMAL,
    SCHEDULE_ACTION_CHARGE_TO_TARGET_SOC,
    SCHEDULE_ACTION_DISCHARGE_TO_TARGET_SOC,
    SCHEDULE_ACTION_STOP_CHARGING,
    SCHEDULE_ACTION_STOP_DISCHARGING,
    SCHEDULE_ACTION_STOP_EXPORT,
}
SCHEDULE_EXECUTOR_INTERVAL_SECONDS = 30
CONSUMPTION_TOTAL_ENTITY_ID = "sensor.helman_consumption_total"
PRODUCTION_TOTAL_ENTITY_ID = "sensor.helman_production_total"
HOUSE_FORECAST_DEFAULT_MIN_HISTORY_DAYS = 14
HOUSE_FORECAST_DEFAULT_TRAINING_WINDOW_DAYS = 56
HOUSE_FORECAST_DEFAULT_MIN_SLOT_POINTS = 2
HOUSE_FORECAST_LOWER_PERCENTILE = 0.10
HOUSE_FORECAST_UPPER_PERCENTILE = 0.90
HOUSE_FORECAST_MODEL_ID = "hour_of_week_winsorized_mean"
FORECAST_CANONICAL_GRANULARITY_MINUTES = 15
FORECAST_GRANULARITY_OPTIONS = (15, 30, 60)
DEFAULT_FORECAST_GRANULARITY_MINUTES = 60
DEFAULT_FORECAST_DAYS = 7
MAX_FORECAST_DAYS = 14
BATTERY_CAPACITY_FORECAST_CACHE_TTL_SECONDS = 300
BATTERY_CAPACITY_FORECAST_DEFAULT_CHARGE_EFFICIENCY = 0.95
BATTERY_CAPACITY_FORECAST_DEFAULT_DISCHARGE_EFFICIENCY = 0.95
BATTERY_CAPACITY_FORECAST_MODEL_ID = "battery_net_load_fractional_hour_v1"
DEFAULT_APPLIANCE_ICON = "mdi:lightning-bolt"
PANEL_FOLDER = "frontend"
PANEL_DIST_FOLDER = "dist"
PANEL_FILENAME = "helman-config-editor.js"
PANEL_URL = f"/api/panel_custom/{DOMAIN}-config"
PANEL_TITLE = f"{NAME} Config"
PANEL_ICON = "mdi:home-lightning-bolt-outline"
PANEL_NAME = "helman-config-editor-panel"
PANEL_FRONTEND_URL_PATH = f"{DOMAIN}-config"

# Solar bias correction storage defaults and keys
SOLAR_BIAS_STORAGE_KEY = f"{DOMAIN}.solar_bias_correction"
SOLAR_BIAS_STORAGE_VERSION = 1
SOLAR_BIAS_SUPPORTED_STORE_VERSION = 1
SOLAR_BIAS_DEFAULT_ENABLED = True
SOLAR_BIAS_DEFAULT_MIN_HISTORY_DAYS = 10
SOLAR_BIAS_DEFAULT_TRAINING_TIME = "03:00"
SOLAR_BIAS_DEFAULT_CLAMP_MIN = 0.3
SOLAR_BIAS_DEFAULT_CLAMP_MAX = 2.0
